### PR TITLE
Refactoring mvr.py

### PR DESCRIPTION
**Pull request by nrgsille76**
Complete refactor of mvr.py including:

1. Avoid importing meshes multiple times
2. Use collection instances for symbol objects
3. Use already imported collections instead of creating new
4. Use object uuids instead of hashlib or collection names
5. Create custom properties for MVR class, name, uuid and reference
6. Fixed matrix transformations
7. Fixed names if they are doubles
8. Importing is now about 10 times faster

### CODE REVIEW

**Comment by vanous** [comment]
I have been testing further: first import works (with the changes i mentioned in the comments). Then, if you re-import the same file again, what happens is that some geometries get duplicated, which should not happen. For that, i use the scene_objects.mvr from the pymvr repo, it loads fast and has good features for testing.

**Comment by nrgsille76** [comment]
> I have been testing further: first import works (with the changes i mentioned in the comments). Then, if you re-import the same file again, what happens is that some geometries get duplicated, which should not happen. For that, i use the scene_objects.mvr from the pymvr repo, it loads fast and has good features for testing.
I see, this indeed should not happen and I catched that issue in my test setup, I will try to fix this.

**Comment by nrgsille76** [comment]
@vanous Should now be fixed with commit ebcaf9a2e0076c84523be5ea979053a8e718be20

**Comment by nrgsille76** [comment]
@vanous  I tried a plenty of methods to check for existing objects. It is no problem for all regular geometries but for symbols it is not easy because it can be the same object with a different transformation, I have no idea how to identify the object if it has the same filename and symdef but is linked to another scene object because the aux data has to be loaded first to have them available if symbols got imported
Maybe you got some ideas for that

**Comment by vanous** [comment]
Thank you. I would have to have a look how it was done before and dive deeper into the mvr code. I remember that for the Geometry3D i generate a hash to be unique based on name and transform [here](https://github.com/open-stage/python-mvr/blob/f8ffef86c809718e45b893662c018d50db2eb2d3/pymvr/__init__.py#L707), so could we perhaps do something similar in this case?

**Comment by nrgsille76** [comment]
@vanous 
Finally made it, looks a bit wierd but works on my side. Latest commit: f7b438ae2377b1022dd371f24a70ae3c94a56c89

**Comment by vanous** [comment]
@nrgsille76 thank you for all the work! Ready to merge?

**Review by vanous — APPROVED** [review]

**Comment by vanous** [comment]
Thank you!* dmx: Update for mvr refactoring

**Pull request merged**
