### PR TITLE
Update io_scene_3ds to LTS version

### PR DESCRIPTION
**Pull request by nrgsille76**
Hi there ;)
Just found this extension on the extensions platform and because I also work as a lighting designer, it is a nice project.
I noticed that you are using the 3ds addon wich I am the maintainer of and I recently completed the project. The 3ds addon is now capable to import and export all possible 3ds data including camera, lights, animations, world and atmosphere settings.
This pull updates io_scene_3ds to the LTS version wich is compatible from Blender 3.4 thru 4.3 (latest).
The addon can also be found on [this repository](https://github.com/nrgsille76/blender-io-addons)
The developing is completed, all further maintaining will be done as extension version in [blender extensions](https://projects.blender.org/extensions/io_scene_3ds)

I also provide fixture profiles in .xml and .gdtf format and some packages with mvr environments on [my website](https://www.nrgsille.com) if you are interested in more information here is my [github account](https://github.com/nrgsille76)

### CODE REVIEW

**Comment by vanous** [comment]
Thank you, I will test, perhaps this will fix some 3DS importing issues.

Do you publish also a python wheel? That would be useful for our extension, rather than vendoring.

**Comment by vanous** [comment]
I have tested this but it seems that changes are required. It seems that  .io_scene_3ds.import_3ds.load now requires a file object?

```

INFO Processing MVR file: test.mvr
Traceback (most recent call last):
  File "dmx/panels/setup.py", line 594, in execute
    dmx.addMVR(file_path)
  File "dmx/dmx.py", line 1488, in addMVR
    process_mvr_child_list(
  File "dmx/mvr.py", line 91, in process_mvr_child_list
    process_mvr_object(
  File "dmx/mvr.py", line 187, in process_mvr_object
    coll = add_mvr_object(
           ^^^^^^^^^^^^^^^
  File "dmx/mvr.py", line 287, in add_mvr_object
    mvr_file_collection = loadModelAndPrepareMvrFileCollection(file, folder)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dmx/mvr.py", line 253, in loadModelAndPrepareMvrFileCollection
    load(None, bpy.context, file_name)
  File "dmx/io_scene_3ds/import_3ds.py", line 1855, in load
    load_3ds(Path(directory, file.name), context, CONSTRAIN=constrain_size, UNITS=use_scene_unit,
                             ^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'

```

**Comment by nrgsille76** [comment]
@vanous  The importer now supports collection import, the folder and file does not have to be joined anymore.
Should be fixed with commit 30001d2dfa1425961fdcdff951f099b7d5f3a2cb

**Comment by vanous** [comment]
Good. We will have to do the same in gdtf.py .

**Comment by nrgsille76** [comment]
@vanous  After testing this by myself I found out that you indeed need a file object. I made some changes, we will use `load_3ds` definition of the importer to parse the filepath. I also added some keywords to filter mesh objects and to convert the size because in Blender every unit is meter while in vectorworks and mvr definition every unit is millimeter. Should be solved now with commit: 46ccc27f2c88946eb510fffd16c5101a56002ea2

**Comment by vanous** [comment]
Thank you. I have tested the MVR import (GDTF import will still need adjusting) and it has been failing with the following:

```python
  File "dmx/mvr.py", line 287, in add_mvr_object
    mvr_file_collection = loadModelAndPrepareMvrFileCollection(file, folder)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dmx/mvr.py", line 253, in loadModelAndPrepareMvrFileCollection
    load_3ds(file_name, bpy.context, CONSTRAIN=0.01, FILTER={'MESH'}, KEYFRAME=False)
  File "dmx/io_scene_3ds/import_3ds.py", line 1777, in load_3ds
    process_next_chunk(context, file, current_chunk, imported_objects, CONSTRAIN, FILTER,
  File "dmx/io_scene_3ds/import_3ds.py", line 688, in process_next_chunk
    process_next_chunk(context, file, new_chunk, imported_objects, CONSTRAIN, FILTER,
  File "dmx/io_scene_3ds/import_3ds.py", line 832, in process_next_chunk
    read_texture(new_chunk, temp_chunk, "Diffuse", 'COLOR')
  File "dmx/io_scene_3ds/import_3ds.py", line 529, in read_texture
    contextWrapper.node_principled_bsdf.inputs[14].default_value = contextReflection
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: NodeSocketFloatFactor.default_value expected a float type, not NoneType
```

As for adjustments, the default scaling is good, we can then remove our scaling:

```python
        if file_3ds:
            # ob.scale = (0.001, 0.001, 0.001)
            ob.scale[0] *= 0.001
            ob.scale[1] *= 0.001
            ob.scale[2] *= 0.001
```

Also, for the MVR import, we do not need to limit this to MESH, as one can import any 3D (3DS) object via MVR, but this filter will be important for GDTFs.

**Comment by nrgsille76** [comment]
@vanous  Strange that I never ran into that issue although I tested it with a lot of 3ds files. Well that also improves my script^^
I added a default value for reflection, should now be solved with commit: 595f0122dc6ce718c05a83a51bad7b1c377b8461

**Comment by vanous** [comment]
So the file loading issue is now solved, but there is a new placement or origin point... issue:

Old version of the loader, correct import:

image


New version, wrong import:

image

thank you

**Comment by vanous** [comment]
i have separated just the single file so you can test... attached is the test mvr, rename from.zip to .mvr...

[test.zip](https://github.com/user-attachments/files/16057604/test.zip)

**Comment by vanous** [comment]
And strangely, only this particular 3DS is in wrong position, all others seem in correct place...

**Comment by nrgsille76** [comment]
@vanous  I checked that file, the reason why this occurs is a incomplete keyframe chunk, the keyframe data is essential for the real object location, rotation and scale, the matrix in chunk (0x4160) defines the mesh orientation in world space and the keyframer defines the hierarchy for object matrix transformation wich also takes parent transformation into account.
The 3ds in the zip only has a keyframe position chunk (0xB020) while rotation (0xB021) and scale (0xB022) are missing, therefore the matrix is incomplete wich results into the wrong transformation. See attached screenshot. Do you know from wich software it was exported?

Screenshot 3ds test

**Comment by vanous** [comment]
> @vanous I checked that file, the reason why this occurs is a incomplete keyframe chunk, the keyframe data is essential for the real object location, rotation and scale, the matrix in chunk (0x4160) defines the mesh orientation in world space and the keyframer defines the hierarchy for object matrix transformation wich also takes parent transformation into account. The 3ds in the zip only has a keyframe position chunk (0xB020) while rotation (0xB021) and scale (0xB022) are missing, therefore the matrix is incomplete wich results into the wrong transformation. See attached screenshot. Do you know from wich software it was exported?
> 

I understand the reasoning, but how come that older version of the 3DS loader placed it into correct position? This new version of the 3DS loader  is creating a regression for us. While i know that the MVR was exported by VWX, i have no idea what produced that file...

**Comment by nrgsille76** [comment]
@vanous  I only tested to import the 3ds directly, usually the object placement is done in the GeneralSceneDescription.xml
If I import one my own mvr files then the objects are also not placed correctly, they are in the position as they were exported at position (0,0,0) the matrix from the GeneralSceneDescription seems to make no difference

**Comment by vanous** [comment]
I have tested few other MVR files and have not seen any further issues at this point. I have also checked some GDTFs i know had been problematic... and i can see differences.. feels similar to the above. These pictures are related to the attached GDTF file.

Loading with previous 3DS loader:

image

Loading now:

image

It actually seems that the models get loaded but now placed properly.

The file is from the share or posted by someone in discord... not sure anymore.

[Sterra@JDC1@dimmers.zip](https://github.com/user-attachments/files/16058331/Sterra%40JDC1%40dimmers.zip)


In general, 3DS seem to be quite problematic... like the "colorsource spot V" in the share (just search for it)... anyways. I can keep providing strange 3DS files but i am not sure if it helps... also, not sure if you like to keep the discussion here. It's fine with me...

**Comment by vanous** [comment]
> @vanous I only tested to import the 3ds directly, usually the object placement is done in the GeneralSceneDescription.xml If I import one my own mvr files then the objects are also not placed correctly, they are in the position as they were exported at position (0,0,0) the matrix from the GeneralSceneDescription seems to make no difference. 

Not sure what you mean, Is this in BlenderDMX? For all your files or just some? Position from MVR is applied to the models while loading the MVR. Is this specific to some of your files or all?

> Can you provide the complete mvr with the malfunctional file? Usually if a part is missing in the keyframer it will take the values from an identity matrix

That was the test.mvr i provided (test.zip, as gh doesn't allow mvr files as attachments), here it is [test.zip](https://github.com/user-attachments/files/16057604/test.zip)

**Comment by nrgsille76** [comment]
I have no problems helping you with that, got a lot of experience with 3ds files. There are a lot of files out there wich made problems but the latest importer was able to catch them all, because of the two different object placements I added a plenty of transform options, we can tweak the importer to do what it should do, for example only take the mesh matrix and ignore keyframe positions

**Comment by nrgsille76** [comment]
@vanous  I played around a little with the script and imported multiple mvr files for testing. I noticed that the matrix has to be transposed, global and local transform has to be exchanged and before that, scale has to be applied.
Maybe your files will now also be imported correctly^^
See commit:  648b05f9521783c701127b7d9be0dc574a1f5a01

**Comment by vanous** [comment]
Yeah, this is a deep rabbit hole :). 

The good news - i cannot see any regressions at this point when loading GDTFs, actually, i can see some improvements (like for the JDC1 file - the model is now imported correctly, even though positioning is not right, but that could be some other thing... good for now), also Cameo fixtures now load completely nicely. :+1: 

As for MVR, this now broke placement during positioning a lot 🙃 :

Before:

image

After:

image

The above is the "scene_objects.mvr" in the [pymvr test folder](https://github.com/open-stage/python-mvr/tree/master/tests). There is also a Capture demo show, i have not tested it now, as it takes a lot of time to load. The Capture demo typically loads 99% correct, except of the roofs, which have never been placed correctly for me.

This does not mean that you are not on the right path. I have spent countless hours on this. Each step is important. The order of the operations of course also matters.

**Comment by nrgsille76** [comment]
@vanous  Yeah I am a little bit disappoined how vectorworks exports the mvr files, not only that the 3ds is not exported correctly but they are also not got a proper generalscenediscription file. But I was able to fix this, Here is a patch, mvr somehow can have the matrix on three differnt places and they have to be combined. I added prints to print out the matrix for each transformation.
Try this out:
[open_stage_blender_dmx.zip](https://github.com/user-attachments/files/16067272/open_stage_blender_dmx.zip)

**Comment by vanous** [comment]
> @vanous Yeah I am a little bit disappoined how vectorworks exports the mvr files, not only that the 3ds is not exported correctly but they are also not got a proper generalscenediscription file. 

Some of my MVR files are declaring MVR 1.4, which is quite old, so perhaps VW is exporting better now, both 3DS and MVR itself.

> But I was able to fix this, Here is a patch, mvr somehow can have the matrix on three differnt places and they have to be combined. I added prints to print out the matrix for each transformation. Try this out: [open_stage_blender_dmx.zip](https://github.com/user-attachments/files/16067272/open_stage_blender_dmx.zip)

I can still see plenty of issues which are not happening with the original import - some objects are not placed correctly, which means that for example all trusses are misplaced. I tested some files from VW and some from Capture and i still see a lot of misplacements, which tells me that the issue perhaps is not in faulty MVR export, but in how we import them. Hard to say. Unfortunately, these files MVR cannot be shared, we would have to figure something out.

I can see that you are using the Extension, there is a dedicated branch for that, with a WIP PR here: https://github.com/open-stage/blender-dmx/pull/178 . If you like to work against that, rather then main, it is also possible, but first see below.

Summary: the io_scene_3ds updated to LTS is already providing quite some benefits to the GDTF import and i am sure also to the MVR imports. When loading 3DS in MVR in this way: `load_3ds(file_name, bpy.context, KEYFRAME=False, APPLY_MATRIX=False)` , MVR is working as before.

What i would suggest: 

- shrink this PR back to only do the io_scene_3ds update, plus the required changes in gdtf.py and mvr.py to use load_3ds() instead of load()
- squash the PR so it is just one commit with this upgrade to LTS

I can then merge it into main and will rebase the [extension](https://github.com/open-stage/blender-dmx/pull/178) branch. If you like to, we can then continue looking at improvements to the MVR imports/handling of the transforms and so on - you can base it on the main or on the extension branch.
What do you think? Do you agree?

**Comment by nrgsille76** [comment]
@vanous  The latest commit ( 454aeaec1e60ccc7243a8fd816223c9ff49b5144 ) works for all mvr test files I found on your site including the ones I have.
Here is a screenshot of the capture scene, the roof got a gimbal lock, wich occurs on 90 and 180 degrees

cameo mvr

**Comment by nrgsille76** [comment]
> > @vanous Yeah I am a little bit disappoined how vectorworks exports the mvr files, not only that the 3ds is not exported correctly but they are also not got a proper generalscenediscription file.
> 
> Some of my MVR files are declaring MVR 1.4, which is quite old, so perhaps VW is exporting better now, both 3DS and MVR itself.
> 
> > But I was able to fix this, Here is a patch, mvr somehow can have the matrix on three differnt places and they have to be combined. I added prints to print out the matrix for each transformation. Try this out: [open_stage_blender_dmx.zip](https://github.com/user-attachments/files/16067272/open_stage_blender_dmx.zip)
> 
> I can still see plenty of issues which are not happening with the original import - some objects are not placed correctly, which means that for example all trusses are misplaced. I tested some files from VW and some from Capture and i still see a lot of misplacements, which tells me that the issue perhaps is not in faulty MVR export, but in how we import them. Hard to say. Unfortunately, these files MVR cannot be shared, we would have to figure something out.
> 
> I can see that you are using the Extension, there is a dedicated branch for that, with a WIP PR here: #178 . If you like to work against that, rather then main, it is also possible, but first see below.
> 
> Summary: the io_scene_3ds updated to LTS is already providing quite some benefits to the GDTF import and i am sure also to the MVR imports. When loading 3DS in MVR in this way: `load_3ds(file_name, bpy.context, KEYFRAME=False, APPLY_MATRIX=False)` , MVR is working as before.
> 
> What i would suggest:
> 
>     * shrink this PR back to only do the io_scene_3ds update, plus the required changes in gdtf.py and mvr.py to use load_3ds() instead of load()
> 
>     * squash the PR so it is just one commit with this upgrade to LTS
> 
> 
> I can then merge it into main and will rebase the [extension](https://github.com/open-stage/blender-dmx/pull/178) branch. If you like to, we can then continue looking at improvements to the MVR imports/handling of the transforms and so on - you can base it on the main or on the extension branch. What do you think? Do you agree?

Did you test the latest commit? I just have fixed the remaining errors. Here is the patched file:
[open_stage_blender_dmx.zip](https://github.com/user-attachments/files/16071472/open_stage_blender_dmx.zip)

I do not know the difference between the main and the extension branch, but I agree ;)

**Comment by vanous** [comment]
Thank you :) I am not a biggest fan of discord, but maybe it would be easier there.

> I do not know the difference between the main and the extension branch, but I agree ;)

The extension branch is based on wheels, while the main is vendoring the used libraries (wheel usage is not possible afaik in blender < 4.2).

> Did you test the latest commit? I just have fixed the remaining errors. Here is the patched file:

Yes, I tested the latest commit, here is what i should see (main branch):

image

here is what this PR produces:

image

I can see similar issues with other MVRs. Problem is MVR sharing :( :(

Could these _maybe_ be shared resources (symdefs?). (i did not check and cannot check right now).

**Comment by nrgsille76** [comment]
@vanous  I do not get the same result with the test file, I only got the back curtain and no truss, the only difference between the 3ds scripts is that the old one aplies the matrix to local space and the new one to world space wich is correct because the lagacy 3ds software only got world space with one matrix

**Comment by vanous** [comment]
I only kept the backdrop in the mvr, not the trusses. I will see if I can create a file which can demonstrate the issue.

**Comment by vanous** [comment]
Yup, as i thought, symdefs. I have made simple mvr which can represent the issue, please try it.
[test.zip](https://github.com/user-attachments/files/16071900/test.zip)

This is what you should see:

image

**Comment by vanous** [comment]
I can actually see lots more issues also on the Capture demo file:

the new import:

image

the not perfect but i think better original import:

image

First time i am hearing about a gimbal lock. I read up on it a bit but am unclear what does it mean in the context of the Capture exported file?

**Comment by nrgsille76** [comment]
@vanous  I guess I found the issue, you are right with the order of transformations, instead of

`global_transform @ Matrix(geometry.matrix.matrix).transposed() `  it has to be
`Matrix(geometry.matrix.matrix).transposed() @ global_transform`

**Comment by vanous** [comment]
@nrgsille76 sounds very good! Do you want to push your changes? I can test on several MVR files.

**Comment by vanous** [comment]
Yep, things are looking very nice now! :)

**Comment by nrgsille76** [comment]
I am cool with pushing, made the fix in commit 2722b2b203554de9ae433d01f711d15f9aa58708

**Comment by vanous** [comment]
Hmm, testing, but found some issues. I can provide a testing MVR but need to DM you somewhere. What is a good way to do this?

**Comment by nrgsille76** [comment]
I made another fix, enumerating the for loops gives a proper runtime and avoids double transformations
864e5e223a9dc376a7a8e352155a3f6989bba25a

**Comment by vanous** [comment]
OK, i sent a request to that username, not sure if it works. If not, please join the group [chat here](https://discord.gg/FQVVyc45T9), thank you.

**Comment by nrgsille76** [comment]
@vanous This can now be pushed if you want, import mvr works like with the old 3ds importer, but now with the new one with the same object transformations. Latest commit: a4a3c417c4fb7f1ee1e0113e1a758e15a45fe26e

**Comment by vanous** [comment]
Tested, looks good! It would be good to squash the LTS commits into a single one and then the subsequent adjustments into another, this is about what the result would look like (i tested the squashing):

* aaf6116 Sun Jun 30 23:09:26 2024 +0200 | Ensure fixture can be removed even data is too broken (HEAD -> sille) [vanous]
* add3a14 Sun Jun 30 22:56:28 2024 +0200 | Add RGB versions of the provided source4 fixture [vanous]
* ac98ee4 Mon Jul 1 12:25:36 2024 +0200 | mvr, gdtf: Adjustments for io_scene_3ds LTS [Sebastian]
* 1308a7d Mon Jul 1 01:07:32 2024 +0200 | io_scene_3ds: Update to LTS version [Sebastian]
* e938deb Sun Jun 23 17:11:07 2024 +0200 | Release 1.6.0 (tag: v1.6.0) [vanous]

Let me know if you need help with this.

**Comment by nrgsille76** [comment]
I merged your commits into my branch by updating yesterday. You could squash or merge like you want

able to merge

**Review by vanous — APPROVED** [review]
Thank you!

**Pull request merged**
