### PR TITLE
Fix initial stumbling blocks

### PR DESCRIPTION
**Pull request by marksteward**
Fix a couple of issues that stopped me using the plugin:

 - sACN messages with a dmxStartCode should be ignored
 - Live DMX display gets stuck

Also tweak a couple of logging levels and wording.

### CODE REVIEW

**Review by vanous — APPROVED** [review]
Looks good, thank you!

**Comment by vanous** [comment]
Thank you very much. 

Note: there is a new architecture being worked on, so we will need to rebase these fixes up to the Development branch at some point.

**Comment by marksteward** [comment]
I'm happy to rebase as long as there's a reasonable way of testing the dev branch.

**Comment by vanous** [comment]
Thank you! Rebasing is easy, this was more of a note not to forget. As for the rewrite - a lot of work has already been done, especially on restructuring the GDTF parsing flow. The new flow is better and modularizes the whole codebase in better way. It also reflects the parent-child relationship of geometries in much better way, allowing to keep correct positions and rotations of geometries, but we must re-implement some previously implemented concepts (geometry references and so on), which for now are not used. I haven't had a chance to look deeply into it to know if we can "just" add the (for example) geometry references stuff or if it requires more complex changes to the parsing flow. (The main thing is that GDTFs must be parsed starting from geometry tree, not from the dmx table).

**Pull request merged**
